# Generated by Django 5.0.7 on 2024-07-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djourneys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
